### ISSUE TITLE
Passing tableNumber through DoGoToSeat

### ISSUE THREAD

**Issue by JPFrancis** [usc-csci201-fall2013/restaurant#1]
I'm having issues figuring out how to pass a tableNumber through DoGoToSeat(). The problem is that SitDown(), which calls DoGoToSeat(), does not receive any parameters. I thought about modifying the SitDown function but then the pickAndExecuteAnAction function (which calls SitDown()) would have to be passed a parameter as well. This doesn't seem right. I also considered making a private variable in the CutomerAgent to hold the currentTableNumber, but that seemed sloppy. Any suggestions for how I should approach this? Thanks.

**Comment by 004forever** [comment]
I went ahead and modified the parameters.  I also made a table class and passed that instead of passing the table number so I didn't have to maintain and move multiple lists of tables.  That just seemed cleaner, but I feel like I broke some sacred rule by doing that.

**Comment by JPFrancis** [comment]
Thanks for the response. I'm still confused about how your managing to pass a variable to SitDown() though since it is called through the pickAndExecuteAnAction() method. Are you calling SitDown() from the Host msgSitAtTable() or some other method?

**Comment by 004forever** [comment]
Oh, I see what you're saying.  Table(or tableNum) should be a variable in customerAgent that gets set when the message is received. At least, that's how I did it.

**Comment by pixelprizm** [comment]
I didn't include the table number in customeragent at all. The waiter agent passes the table number to the waiterGui, which then translates that number into the correct x-y coordinates, then passes those coordinates to the customerGui.  The customerGui doesn't start moving until it receives both a DoSitDown message from customerAgent and the coordinates from WaiterGui.  That's the way that Wilczynski suggested yesterday.

**Comment by JPFrancis** [comment]
Yeah, this was earlier, before I had any waiters. I'm chillin now. Thanks.

**Comment by alghanmi** [comment]
@jpfranci, I am assuming you got a satisfying response to this issue. As such, this issue will be closed.
