### ISSUE TITLE
Importing junit failure

### ISSUE THREAD

**Issue by jdgreenberger** [usc-csci201-fall2013/restaurant#102]
When I clone my repository and try to run my cashier test, there is an error when trying to import "junit.framework.TestCase". Does anyone know why this is happening/how to fix it?

**Comment by jlazzaridean** [comment]
you have to add JUnit to your build path...Right click on the package and go to Properties -> Java Build Path -> Libraries -> Add Library -> JUnit -> JUnit 3 (or JUnit 4). It worked for me after that.

**Comment by dacaraway** [comment]
This means that the grader will have to add the JUnit to the build path also... Won't we Lose points for that? @alghanmi

**Comment by choiRyan** [comment]
This was answered before; no

**Comment by cather** [comment]
No, #93
