### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by lizhifan** [usc-csci201-fall2013/restaurant#106]
Are we supposed to have issues in our restaurant_name github? Because I only have the previous issues and the issue saying with the grade for v 2.1

**Comment by clay-to-n** [comment]
I don't believe anyone has them.  I'm assuming that making your own issues and closing as you go is optional.

**Comment by alghanmi** [comment]
@clay-to-n is correct.

**Comment by lizhifan** [comment]
sorry, just making sure. This is optional to create your own issues and close them right? Or is it a required part of this project?

**Comment by alghanmi** [comment]
It is not required, i.e. optional.
