### ISSUE TITLE
GUI animation dragging and freezing

### ISSUE THREAD

**Issue by paigekehoe** [usc-csci201-fall2013/restaurant#107]
My cook animation leaves a large block of color in its wake - it redraws itself, but leaves the old location still drawn as well, at least sometime, see pic:
![screen shot 2013-11-03 at 8 09 37 pm](https://f.cloud.github.com/assets/3280005/1462763/2427ca40-4507-11e3-9d92-466d00e48358.png)

Then it freezes randomly when the cook starts to make an order.

Some other issues mentioned this is a synchronization issue, but I already changed the synchronized() to try/catch and it still freezes and drags. 
This might also be two issues - the synchronization and the freezing, but they both started happening at the same time.  Anyone know how to fix this?

**Comment by diegovb** [comment]
Inside RestaurantGui there is a method that clears the animation panel by drawing a gray block over everything before redrawing everything again. Maybe you want to look there to find out why the cook is leaving a trace.

**Comment by shanemileham** [comment]
I agree with @diegovb. The dimensions of that grey block are at the top of AnimationPanel and don't exactly correspond to the ones specified in the RestaurantGui. Enlarge the block so it will refresh, and you shouldn't have those problems anymore.
