### ISSUE TITLE
Cook Animation

### ISSUE THREAD

**Issue by Jacobliber** [usc-csci201-fall2013/restaurant#11]
@alghanmi 

I don't see any way add a label to this issue.
LABELs: v2, Question, Animation

Hi,

The rubric indicates the cook should be offscreen. I have my cook on screen and waiters go to him to place and pick up orders (the cook doesn't move). Is that ok, or do I need to move him?

Thanks

**Comment by Valakor** [comment]
As far as I know, the cook doesn't actually have a GUI and isn't seen on-screen (he's just an invisible location off-screen).

**Comment by lshiffer** [comment]
My cook is on screen too, same thing.  Waiters walk over to Cook to place orders and then return to pick them up.
