### ISSUE TITLE
Why has adding a new add waiter panel disabled the waiter gui?

### ISSUE THREAD

**Issue by rysheh** [usc-csci201-fall2013/restaurant#12]
My waiter gui was working with one single waiter, but after adding the add waiter panel and adjusting restaurant panel and the waitergui constructor to work similar to that of customer gui, it doesn't show at all.

**Comment by meldefon** [comment]
If I'm understanding correctly, I had a similar problem. Did you make sure to start the WaiterAgent thread? Also, in my code, the gui stuff didn't change after adding a waiter until I put a "validate()" in the code that adds a waiter. You need that when you add any new component and you want it to be drawn (I think). 

Best,

Gabe

**Comment by rysheh** [comment]
It could be the thread...however I started the waiter's thread in the same location as the customer's thread in RestaurantPanel.addPerson(). I'm not sure if that's incorrect. 
I'm wondering, where did you add validate()? I had the impression that validate() was adequately added in for us, such as in ListPanel.addPerson().

**Comment by meldefon** [comment]
I added an entirely new class that works like ListPanel, but adds waiters. At the end of the addWaiter function, I put validate(). Then, everything seemed to work.

**Comment by Jacobliber** [comment]
Hey,
Did you make sure that the new waiters that get created are given pointers to the host and that host has the new waiter pointer in his waiter list? If not, then the waiter might not move because it wont send and receive messages.

Also, is the restaurant supposed to start with at least one waiter or start with no waiters until thy are added by the gui?

Good luck.

**Comment by rysheh** [comment]
Ah, I'll try that and see if that works. And I can't really answer your question about starting w/ one waiter vs. no waiters, but I know others who've hard-coded one waiter to start with.

**Comment by Jacobliber** [comment]
The rubric indicates that there should be 0 waiters to start.

**Comment by rysheh** [comment]
So the host DOES receive the waiter pointer, but the animation for the waiter alone hasn't shown....
As mentioned before, I have the gui set, and the thread started in the RestaurantPanel.addPerson(), all the actions run perfectly, and the customer gui shows, and the waiter gui SHOWED when it was only one waiter and not a list of them. The only problem is after I added an add waiter panel, the waiter gui stopped showing.
