### ISSUE TITLE
Pulling from github and running on Eclipse

### ISSUE THREAD

**Issue by dacaraway** [usc-csci201-fall2013/restaurant#13]
If we want to check to make sure we have everything pushed and want to pull and run it to make sure, how do we go about opening the pulled files and running them on eclipse?

**Comment by ghost** [comment]
Maybe just clone the repo to a new location on your machine, import the project (I believe it's File->New->Eclipse Project from existing ANT build file), and make sure it builds and runs successfully.

**Comment by alghanmi** [comment]
@dacaraway, details are on the [submission instructions](http://www-scf.usc.edu/~csci201/submission-instructions.html) page.

@sciencepro right on point..

Rami
