### ISSUE TITLE
Animation not in line with actions being called

### ISSUE THREAD

**Issue by richy0101** [usc-csci201-fall2013/restaurant#14]
My waiter gui is freaking out whenever an action is called from waiter agent. All the interactions of messages and actions work but when I call on the gui to change the waiters destination according to where he is supposed to go, he will go back and forth between its previous location and new location a few times before doing another action. I'm not sure why this is

**Comment by ghost** [comment]
Make sure you have some way of ensuring an animation is completed before moving on to another action or running another animation.  One method suggested by a CP is using a semaphore, which works well.
Add print statements to virtually every action, message, and animation so you can trace through and find exactly what is getting called more than once (maybe a state isn't being properly updated somewhere)
