### ISSUE TITLE
Cloning

### ISSUE THREAD

**Issue by waynchi** [usc-csci201-fall2013/restaurant#16]
I'm cloning my repo to test it out, but I can't seem to pull anything from the build portion(Where my pictures are located) Is there a workaround to this?

**Comment by ghost** [comment]
Why are you putting the images in the build directory?  This is where the compiled class files go...ideally it should be in your src directory or some other resource directory.  (If I'm wrong about any of this, feel free to correct me).

**Comment by maciesielka** [comment]
I couldn't actually get my image files to copy over using the buildfile either...my images are located in a `res/` file in the folder that my repo clones into. I just walked my grader through how to import those files in using a "Run Instructions" section of my README. 

Will this work? @alghanmi , I figure you would be the one to ask.

Thanks

**Comment by alghanmi** [comment]
@maciesielka, writing that in the `README` file is more than enough. However, I would recommend checking my response in #18 on a way that will make it work better/easier. Let me know if it works for you.
