### ISSUE TITLE
CP compilation potential issue

### ISSUE THREAD

**Issue by Seioch** [usc-csci201-fall2013/restaurant#17]
@alghanmi 
I read on the rubric that the README.md should have a way of compiling the code so that it will compile correctly. However, my code has pathways to files on MY computer, so if someone else were to download my code and try to compile, it wont compile the images and throw a bunch of "cannot find <name>.png" errors. 
1. Can we upload the compiled, cleaned .jar file and instruct the CPs or TAs to grade us based on that?
2. Is there a way to change the directory in the code so that it will always find the image when downloading the picture off github?
3. Are we allowed to change the .gitignore to allow us to upload other files pertinent to the PA?

Thanks,
Kenneth Chang

**Comment by alghanmi** [comment]
@Seioch:
1. **NO**
2. Yes, see my response in #18 
3. You can change the `.gitignore`, however, if you include any binaries, object files, executables and/or Eclipse specific files such `.project` you **will** be penalized.

Hope this helps..

**Comment by Seioch** [comment]
Another question: I can't get a scanned copy of my design docs into Github. Where else can we submit it? I remember there was somewhere on campus that we could turn it in.

**Comment by alghanmi** [comment]
Professor @dwilczyn mentioned the following in an email he sent on the 27th:

> There are many important issues in this email. 
> Everyone, students and CP's, read it CAREFULLY.
> ...
> The design document can be added to your repository in any electronic format including a scanned version of a paper-based design. You also have the option to submit a hard-copy of your design document by the deadline using our locker #5 adjacent to the water cooler next to SAL 106.

**Comment by Seioch** [comment]
Relative paths do not work. I've tried:

hostIcon = ImageIO.read(new File("data/Host.png"));
hostIcon = ImageIO.read(new File("/data/Host.png"));

But both throw errors. Help?

**Comment by Valakor** [comment]
Try making the ' / ' a ' \ '. Different file systems use different slashes.

**Comment by ghost** [comment]
`File.separator`  should get you the right one based on your OS...

**Comment by Oceane** [comment]
I tried that and it didn't work

**Comment by Oceane** [comment]
What do you mean by File.seperator

**Comment by Oceane** [comment]
Ignore the last comment it still didn't work
I'm using a mac OSX 10.8.4 Is there a way to fix that?

**Comment by alghanmi** [comment]
Are you sure your `data` directory is in the root of your project and not under `src`?
