### ISSUE TITLE
Concurrent Modification Exception for ArrayList

### ISSUE THREAD

**Issue by jlazzaridean** [usc-csci201-fall2013/restaurant#2]
Sometimes when a customer is leaving, I get the following error (c4 is the customer, Samuel is the waiter, Sarah is the host):
c4: Leaving.
Samuel: customer c4 leaving table 1
Samuel: Clearing 1
Sarah: restaurant.HostAgent@bed1fd has reopened table 1
c4: Unexpected exception caught in Agent thread:
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    at java.util.ArrayList$Itr.next(Unknown Source)
    at restaurant.WaiterAgent.msgDoneEatingAndLeaving(WaiterAgent.java:97)
    at restaurant.CustomerAgent.leaveTable(CustomerAgent.java:227)
    at restaurant.CustomerAgent.pickAndExecuteAnAction(CustomerAgent.java:150)

This causes the customer to freeze at the table and not leave the restaurant. All discussions of this error that I have found say that it comes from adding/deleting from an ArrayList while iterating through it, but as far as I can tell, I'm not doing this. Has anyone else had this problem?

**Comment by 004forever** [comment]
As sort of a quick fix, I've been replacing any for loops formatted like for(MyCustomers mc : customers) with for(int i = 0; i < customers.size();i++) and using customes.get(i) to get an element instead of mc.  That's cleared up the issue, but I don't know if that's the ideal solution.

**Comment by jlazzaridean** [comment]
That seems to have cleared it up, thanks so much! I spent forever trying to figure out where I was modifying and iterating at the same time. Any ideas as to why the foreach loops set off the error and the regular for loops don't?

**Comment by dwilczyn** [comment]
Ignore concurrent modification exceptions for now. We will talk about them
later. If it happens, just restart your program.

Prof. W.

On Thu, Sep 26, 2013 at 10:10 PM, 004forever notifications@github.comwrote:

> As sort of a quick fix, I've been replacing any for loops formatted like
> for(MyCustomers mc : customers) with for(int i = 0; i <
> customers.size();i++) and using customes.get(i) to get an element instead
> of mc. That's cleared up the issue, but I don't know if that's the ideal
> solution.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/usc-csci201-fall2013/restaurant/issues/2#issuecomment-25223490
> .

## 

Professor David Wilczynski
USC Dept. of Computer Science
Office: SAL340
213-740-4507

**Comment by jlazzaridean** [comment]
Close #2
