### ISSUE TITLE
Unable to compile cloned repository in Eclipse

### ISSUE THREAD

**Issue by jdgreenberger** [usc-csci201-fall2013/restaurant#20]
I successfully cloned my repository to a new folder and added the project to Eclipse. After I try to run the code, however, I get the following error.

Activation.main: an exception occurred: java.rmi.server.ExportException: Port already in use: 1098; nested exception is: 
java.net.BindException: Address already in use

Does anyone know what this error is or how to get rid of it?

Thanks

**Comment by janicejl** [comment]
Open up the file RestaurantGUI.java, then press run -> Run as Java Application.

**Comment by jdgreenberger** [comment]
That worked perfectly, thank you!

**Comment by alghanmi** [comment]
Remember to close the issue if it is resolved!!
