### ISSUE TITLE
Does "Supress Debug Messages" also mean removing Print information about Agent interactions?

### ISSUE THREAD

**Issue by Valakor** [usc-csci201-fall2013/restaurant#21]
The submission instructions state that we should remove/suppress all debug messages so as to make it easier on the graders; however, in the case of this assignment should we leave in Print() or Do() statements that explain the interactions between Agents?

For example, when my Waiter gives a Customer his food, the Waiter prints a statement saying as such: "Waiter Joe giving Customer Bob his food."

Should we leave this in to make grading easier, or remove them?

**Comment by alghanmi** [comment]
@Valakor, the submission instructions are meant to be as generic as possible that is why the statement you mentioned was preceded by

> unless otherwise noted in the assignment write-up, corresponding rubric or explicitly instructed by the professors

I do believe you should leave the interaction message, however, messages like:

```
I am here
```

```
Agent worked!
```

```
Inside if statement
```

should be suppressed.

**Comment by Valakor** [comment]
Okay, thanks!
