### ISSUE TITLE
Question about deductions

### ISSUE THREAD

**Issue by Narwhalprime** [usc-csci201-fall2013/restaurant#23]
One of the deductions is:

(-5 points) Not using the agent methodology correctly: 
o    Shouldn't pass pointers in messages (other than agent pointers).

1) Does this mean we cannot pass, say, ints and strings into parameters of message methods?
2) Does this mean that we get knocked off 5 points when this happens once, or does this imply bigger penalties the more we do so?

**Comment by Valakor** [comment]
While I'm not sure about Strings (though I think they're excluded in this case), primitive types are passed by value in Java so you aren't using pointers. Other than the Menu and Agents (e.g. the Agent who sent the message), no pointers should be passed.

**Comment by lshiffer** [comment]
So can we pass a String?  I pass a string from Customer to Waiter and again to Chef.  Ints I pass too but guessing those don't count.

**Comment by Valakor** [comment]
There's no way to get around passing Strings, as they represent the choices of customers (unless you used some esoteric int to represent choices and used switch/case every time but I don't think they want us to do that). 
Basically I think Strings are fine.

**Comment by Narwhalprime** [comment]
Eventually it'll be too late to revise this anyway, so for now I'm wondering if someone could clarify the grading above. Another possibility with the deductions is that, since they list five possible ways to deduct points under the header "-5 points", I'm hoping this passing-pointers would only be -1... but I can't tell. Is this how deductions work or is it a flat -5 for passing-pointers-in-messages issue alone?

**Comment by janicejl** [comment]
(1) Strings are fine. Parameters like ints are also fine. 
(2) It implies bigger penalties the more you do so. 

Hope that helps.
