### ISSUE TITLE
Can't build from ant build file

### ISSUE THREAD

**Issue by 004forever** [usc-csci201-fall2013/restaurant#25]
I'm trying to recompile my project in another directory, but I keep getting an old version of the project.  It looks like git is not letting me update the build files for the new agents I've created.

**Comment by alghanmi** [comment]
You **must not** push your compiled (i.e. build files) to your repository this will warrant an automatic penalty. You should get rid of those.

The graders will compile the code themselves with the instructions you provided.

Try cloning the project after removing the class files and importing the testing repo into eclipse. For details check the submission instructions
