### ISSUE TITLE
Cloned my project, Old project doesnt compile now

### ISSUE THREAD

**Issue by richy0101** [usc-csci201-fall2013/restaurant#26]
I cloned my project to the desktop and then created a new project in eclipse from the build.xml file. I tried running it and I got the error message "Activation.main: warning: sun.rmi.activation.execPolicy system
property unspecified and no ExecPermissions/ExecOptionPermissions
granted; subsequent activation attempts may fail due to unsuccessful
ExecPermission/ExecOptionPermission permission checks. "

Then I tried to compile my old project and i get the same error. What is this about?

**Comment by Valakor** [comment]
I would suggest skipping Eclipse altogether. Instead, clone the repo, then open that repo in Terminal (or git bash) and type:

```
$ ant compile
$ ant run.gui
```

Ant is what we're using to compile and all that anyway, so running `ant` will show you the available options. I know Macs have it built-in (at least I did I believe), but I'm not sure about Windows.

**Comment by richy0101** [comment]
All i had to do was run as java application and then build.
