### ISSUE TITLE
GIT push error

### ISSUE THREAD

**Issue by jdgreenberger** [usc-csci201-fall2013/restaurant#28]
I'm trying to add my readme and design doc to my repository but in the process of doing "git push" I got this error:

error: failed to push some refs to 'git@github.com:usc-csci201-fall2013/restaurant_jdgreenb.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
hint: before pushing again.

**Comment by jdgreenberger** [comment]
Is there a way to just push all of my code in one big batch so you don't have to go fetching through my commits?

**Comment by ghost** [comment]
Have you made commits from another machine such that your local copy is behind?

In terms of pushing multiple files, you can add multiple files to be commited with `git add`

**Comment by jdgreenberger** [comment]
I don't think so, I do all my work on one computer.

What I mean by the previous question was is there a way to submit all the files in one commit? Usually the commit only tracks files that have had changes in them.

**Comment by ghost** [comment]
I guess I don't quite understand your question. If a file has no changes, there is nothing to commit. The graders will get a full copy of your repo that the script pulls down.

**Comment by jdgreenberger** [comment]
Ignore the last part then, I just need to figure out a way to push my design document and readme file

**Comment by ghost** [comment]
Copy them into the working folder, `git add` them, commit, and push, should do the trick.

**Comment by jdgreenberger** [comment]
By working folder, do you mean the root project folder? I added them and am still getting the error.

**Comment by lshiffer** [comment]
I can't push either ever since doing a git add . -A
