### ISSUE TITLE
Can't clone repository

### ISSUE THREAD

**Issue by VanceL** [usc-csci201-fall2013/restaurant#29]
I created an alternate folder called test_Location and tried to clone my data there using the  git clone command (I'm in my repository and the command line has [master]) but it says that repository can't be found. What should I do?

**Comment by ghost** [comment]
On the right hand side of the page for your repository on github, you should see a HTTPS clone URL, is that what you're using to clone?

**Comment by VanceL** [comment]
I'm using the git shell command line to pull. Should I be using the clone URL?

**Comment by ghost** [comment]
The clone URL certainly works, but either should be fine...

**Comment by jdgreenberger** [comment]
This might be your problem:

Don't copy the URL from the submission guideline, it is from a repository from last spring. Use this url:

git@github.com:usc-csci201-fall2013/restaurant_ttrojan.git

**Comment by VanceL** [comment]
Thanks! That was the problem!
