### ISSUE TITLE
Different Scenarios

### ISSUE THREAD

**Issue by BachDinh1994** [usc-csci201-fall2013/restaurant#3]
I'd like to know how certain scenarios must be performed:

For example,
2. Multiple customers, one waiter
Add customer; nothing happens. Add waiter; normative scenario should start.
Add another customer. Should be seated at second table
Then, make customer hungry again.

Does this mean that the waiter first seats the first customer, then goes back to seat the second customer, then goes back to the first table for an order?

**Comment by dwilczyn** [comment]
Dear Dinh: The timing makes such distinctions impossible to control. It
should handle all of those cases no matter what the particular timings
happens to occur.

Prof. Wilczynski

**Comment by BachDinh1994** [comment]
I see. Nevertheless, what standard will the graders follow for this particular scenario? Will they start the normative scenario and make the other customer hungry immediately, or will they wait for certain events to occur? The reason I'm asking is that graders may make the new customers hungry so fast that the list of waiters in HostAgent doesn't have enough time to update itself.
