### ISSUE TITLE
Reading .rtf files

### ISSUE THREAD

**Issue by jdgreenberger** [usc-csci201-fall2013/restaurant#30]
When opening my design doc and read me (which are .rtf files), they appear with a bunch of extra characters/code. Should I change the file type, or is this okay?

**Comment by alghanmi** [comment]
Since rtf readers are not standard, I suggest one of the following formats:
- Markdown
- PDF  
- Plain text
- Scanned Image

I would accept LaTeX too :)

**Comment by alghanmi** [comment]
It is worth noting that
1. MS Word documents are no longer an accepted format
2. All documentation must be in a stand-alone documentation directory
