### ISSUE TITLE
Late Submissions Question

### ISSUE THREAD

**Issue by lshiffer** [usc-csci201-fall2013/restaurant#31]
Does submitting within the one hour grace period require the additional steps for grading as mentioned in the email "Late Submissions, v2 Scores and Grading Disputes"?

Also, "Whether or not you want to use one or both of your grace days", we have grace days?

**Comment by alghanmi** [comment]
Submitting within the one hour grace period, i.e. on or before 11:59:59pm does not require any action from your part. However, if your submission was pushed on or after 00:00:00am, you need a late submission request.

No. There are no grace days and that language was removed.
