### ISSUE TITLE
Non-Normative Scenarios

### ISSUE THREAD

**Issue by choiRyan** [usc-csci201-fall2013/restaurant#33]
I'd like two clarifications on the non-normative scenarios, thanks.

What is expected to happen when a customer orders food that he can't afford?

Is this an acceptable way to have a customer leave if all food is expensive?
-Customer calls waiter (ready to order)
-Customer then tells waiter he cannot afford anything
-Customer follows waiter to exit. (Re-enable customer, free table, remove from lists, etc)

**Comment by EliteSoba** [comment]
> What is expected to happen when a customer orders food that he can't afford?

Dine and dash? If you can get the WaiterAgent or HostAgent to catch the running CustomerAgent and call some CopAgents to arrest the CustomerAgent in question, I'm sure you'll get some extra credit points. If you can throw up a Jail Simulation running side-by-side with the Restaurant, I'm sure that's an automatic A.

**Comment by shanemileham** [comment]
@EliteSoba - Didn't you forget about the LawyerAgents and Court Simulation? I'm pretty sure you need a CS201StudentAgent which implements the ExpertWitnessAgent interface. I'm currently stuck on the CS201StudentAgent action finishRestaurantProject(), which is taking a lot longer than it should.

**Comment by maciesielka** [comment]
Should we allow something like this to happen? One of the other requirements says that if the Customer can only afford the cheapest item, he will order it, so by that logic he is already considering costs and wouldn't order something he can't afford, right? I'm just finding that the case "Customer orders, eats, but hasn't enough money to pay" conflicts with the logic we will already be implementing, so should we randomly decide if the customer will be a bad person and order something he can't afford, or just ignore this type of case altogether.

**Comment by choiRyan** [comment]
From lecture: yeah, it's random whether or not the customer orders something he cannot afford. The punishment is up to you, you design your own.

( resolves #33 )

**Comment by diegovb** [comment]
They said the complete opposite in lecture today :/ Just FYI

**Comment by FluffySheep** [comment]
^From lecture today. "The customer must be allowed to pay next time"

What I originally had: Kill the customer if he did not have enough money and tried to pay. His dead body would be dragged by a waiter to a dead customer pile in the bottom of the screen. I asked if I could keep this and the answer was no.

**Comment by choiRyan** [comment]
Killing the thread may have been extreme... My design literally goes and
does the dishes for a time corresponding to how much he's in the red, then
leaves with zero cash and I got the impression that it is okay.
Cp/instructor feedback appreciated here, considering instructions were
design your own response.

**Comment by Yunying** [comment]
My design is also to let the customer wash dishes for a while (The working time depends on how much money he owes the restaurant) and I was wondering if I can keep the design....

**Comment by FluffySheep** [comment]
Nah my customer's thread is still running. He just has a label saying he is dead and he is dragged by the waiter to the bottom of the screen where a pile of dead customers accumulate. Comment on my open issue if you want clarification as to whether you need to change your design or not.
