### ISSUE TITLE
Market-Cook and Cashier scenario Questions

### ISSUE THREAD

**Issue by gabelew** [usc-csci201-fall2013/restaurant#34]
Market-Cook
1. Are the different markets supposed to have more of a certain food or are they all supposed to be random? 
2. Does the cook attempt to order from just one market first and then try to order from the next market if his order isn't fully fulfilled by the first market?
3. The rubric mentions that the cook can also order from the market not just in the cooking action - would putting it at the bottom of the scheduler suffice? (Ordering from the market when there is nothing else to do in the scheduler)

Cashier
1. Do we instantiate each customer with a random amount of money?

**Comment by vikrantsinghal** [comment]
For your first question about the market, it will be a good idea to have different inventories/ initial amounts for different markets. That's what Dr. Wilczynski said in class. They should be such that, you can easily be able to test all the scenarios related to the cook and the markets. So yes. It'll be a good idea to set the inventories manually, which is trivial.

**Comment by ekilah** [comment]
Market/Cook
1. The above comment is what I would have suggested.
2. Sounds logical and a good strategy for now. The market running out of food would be, in my mind, a rarer occurrence in the real world, so I would think this would suffice.
3. Your plan here also sounds reasonable. If the cook is bored, why not check the inventory?

Cashier
1. Similar to the above comment, wouldn't it be much better (and fairly easy) to make this user-controllable? It would make testing actually possible. There are many strategies for this, including using special names or making a GUI for setting it.
