### ISSUE TITLE
v2.05 question

### ISSUE THREAD

**Issue by diegovb** [usc-csci201-fall2013/restaurant#35]
I have a couple of questions:
- Is the code on our v2.05 going to be graded for anything?
- we don't need to tag the commit until our lab section, right?

Thanks!

**Comment by RobertTJ** [comment]
I don't know about the grading, but you should tag it before 11pm tonight.

**Comment by alghanmi** [comment]
v2.05 is used for lab and demonstrations purposes only.

You could tag your submission before hand if you wish or you can wait and tag it after the fact. You need the `v2.05` tag be on the commit used for "grading" (in this case, demoing), i.e. the commit you got in the confirmation email.

**Remember** for actual graded assignments:
- As noted in the Submission Instructions, tasks 1 through 3 should be performed before the deadline. Then, you would confirm that the commit ID your received via email is actually the same commit your regard as your official submission.
- In lab 07, we did not go over preparing your code for submission. This is the zeroth step of any submission and you must follow the instructions stated in Step 0 of the Submission Instructions for your submission to be valid.

**Comment by aitbayev** [comment]
I have no issues created in my private repo!

**Comment by diegovb** [comment]
I think they said they'll be created soon,  I don't either

**Comment by nurkenn** [comment]
Umm Rami, I don't think I actually received the confirmation e-mail. I get the issues showing up however...

**Comment by ghost** [comment]
I got three confirmation emails, you can have one :P

**Comment by nurkenn** [comment]
Sure, if the SHA matches

**Comment by alghanmi** [comment]
@nurkenn, please check your spam folder just in case your email client was mad at me ;).

ITS cause some trouble due to the mass emails, hence, @sciencepro got an extra dose. If you still did not get an email, please create an issue on your private issue tracker and assign it to me.
