### ISSUE TITLE
v2.05 question

### ISSUE THREAD

**Issue by waynchi** [usc-csci201-fall2013/restaurant#36]
What happens if we already tagged something as v2.05 when previously working?

**Comment by alghanmi** [comment]
Use `v2.051` or something similar for lab 7.

**Comment by waynchi** [comment]
Ok thank you. Do we have to do those three steps before 11 P.M. today? Or before lab ends?

**Comment by alghanmi** [comment]
The email announcement stated:

> This assignment **does not** require any action on your part.

Just follow the instructions in Lab07.Part 1.

**Comment by waynchi** [comment]
Ok thank you I just wanted to double check
