### ISSUE TITLE
Running Non-Norms

### ISSUE THREAD

**Issue by amymelody** [usc-csci201-fall2013/restaurant#37]
The v2.1 requirements say that we should tell the graders in our readme how to test the non-normative scenarios. Does this mean that we can include hacks that make it easier for the graders to test these (such as naming a customer "steak" so that he orders steak every time until it eventually runs out)?

**Comment by alghanmi** [comment]
It is extremely preferable to make grading non-norms easy. Graders expect to easily see, spot or trigger non-norms.

If you program non-norms to show-up at random and the grader does not see them after a couple of runs, you will not get points for them.

I found that the best way to trigger non-norms and what students used in the past was to use keyboard or menu shortcuts, e.g. `Ctrl`+`S` automatically depletes the kitchen of all its steak.

I leave this to your creativity and imagination.
