### ISSUE TITLE
Grading lab deadlines

### ISSUE THREAD

**Issue by Narwhalprime** [usc-csci201-fall2013/restaurant#38]
I read the following statements on the assignments page:
- "This lab is worth 10 points. Unsuccessful completion of this lab will result in the loss of lab points and 10 points from the overall Restaurant v2 assignment.
- "Due Date 1 – Lab 06: No milestones. Either study for midterm 1 or start work on v2.1"

I'm confused because I thought lab 06 required us to finish some of the milestones (waiter going on break and cook running out of food). In particular, I'm concerned that 10 points will be docked overall, since I may lose 2 lab points for lab 06 because I didn't finish the waiters-on-break scenario on time. However, I did go to lab on time, I got the other scenario working, and the statement above states no milestones HAD to be completed. So will I be docked a flat 10 points overall because I missed a few points for lab 06?

**Comment by alghanmi** [comment]
The assignment requirements was not updated after the exam was moved. However, the [Lab06](http://www-scf.usc.edu/~csci201/labs/lab06.html) write-up was updated with all the details.

If scored 70%+ in the lab, that would be enough to void the 10pt deduction.
