### ISSUE TITLE
Closing Issues via Commits

### ISSUE THREAD

**Issue by danielCantwell** [usc-csci201-fall2013/restaurant#39]
On the website it says, "When you complete an issue, you must indicate that in your commit message." Can we close them manually on github.com? I made commits for some of the requirements before they were actually issues that we had to close, so if I create new commits to close these issues, the commits won't really correspond to these issues.

**Comment by alghanmi** [comment]
Your concern is addressed in the [Workflow FAQs](http://www-scf.usc.edu/~csci201/git/workflow-single-dev.html):

> What to do if I did not close an issue using a commit message?

Give it a try.
