### ISSUE TITLE
Do we need to fix concurent modification problems for v2.1?

### ISSUE THREAD

**Issue by Simon-Hou** [usc-csci201-fall2013/restaurant#42]
I remember that we go over synchronized list in class. Do we need to implement those?

**Comment by ghost** [comment]
Per v2.1 rubric http://www-scf.usc.edu/~csci201/assignments/rubric02.html, deductions are only for "Runtime errors other than concurrent modification errors, which we ignore for now."

**Comment by Simon-Hou** [comment]
I saw the requirement. Just to make sure. Thank you so much!
