### ISSUE TITLE
Issue # 19 : Animation: Customer Leaving

### ISSUE THREAD

**Issue by dhakiki** [usc-csci201-fall2013/restaurant#43]
One of our issues requires "Animation support for Customer leaving after restaurant runs out of your choice". 

Although in the assignment we are to give the customer the option to choose something else from the menu. I'm confused about how to close that issue..

**Comment by choiRyan** [comment]
Sure the customer could pick something else from the menu, (or lie about
his cash to order something that is available) but if he doesn't, _OR_ all
the food from all the markets and the cook are at stock=0 the customer
would eventually have to leave.
