### ISSUE TITLE
KeyListener

### ISSUE THREAD

**Issue by chadmart** [usc-csci201-fall2013/restaurant#44]
How do you get a KeyListener to work?
I don't think I understand what has focus while everything is running or how to force something to have focus.

I am trying to put hacks in to set the inventory values.

**Comment by choiRyan** [comment]
Did you add a KeyListener to your JTextFields?

The component in focus is basically the component that is highlighted. Not
sure if labels can be focused, but textfields can.
Source: Java API

**Comment by chadmart** [comment]
I can type in my textfields, but I cant figure out how to get keyboard input while a text field is not in focus. like pressing "ctrl + s" to set the cooks steak amount to 0.

I have tried making my restaurantPanel, restaurantGui, and animationPanel implement KeyListener, and then doing an addKeyListener(this) in the constructor. But the KeyPressed method never gets called on any of the classes.

**Comment by ekilah** [comment]
Something like this might help. Note that other components can be KeyListeners besides text fields.
http://stackoverflow.com/questions/5970765/java-detect-ctrlx-key-combination-on-a-jtree

**Comment by ivandavid14** [comment]
you should use key bindings instead
http://docs.oracle.com/javase/tutorial/uiswing/misc/keybinding.html
they are much easier to use and are cleaner. instead of using something like ctrl + s, you can use the function keys too
