### ISSUE TITLE
The Menu

### ISSUE THREAD

**Issue by RobertTJ** [usc-csci201-fall2013/restaurant#5]
Is the menu parameter passed during the msgFollowMeToTable a necessary part of v2?  If so, what are it's specific requirements?  I don't recall it being mentioned in class, or I missed that day, and I currently have it "implemented" as just a printed message where the waiter says the menu is on the table.  Is this satisfactory?

**Comment by BachDinh1994** [comment]
Definitely yes. It's in the UML diagram we did in class. The only requirement is that it contains the various types of food. To be honest you can just instantiate the menu inside the customeragent class, but Professor Wilczynski won't like that since agents don't create stuff.

**Comment by eerie444** [comment]
Agents don't create _other agents_. Agents can create arbitrary objects like `Menu`s or `Order`s.
