### ISSUE TITLE
Waiter's break button question

### ISSUE THREAD

**Issue by Seioch** [usc-csci201-fall2013/restaurant#50]
The requirements on the site go as follows:

When the on-break button is pushed, the waiter will ask the Host for permission to go on break. The host might deny this request if he is the only waiter. If the host gives permission, the waiter finishes all his current customers, then goes on break. The waiter goes back to work when the button is pushed again. <b> Your animation should manage the button correctly: it should be disabled while the waiter and host are negotiating; it should be reenabled if the host denies the waiter</b>; it should say "back-to-work" while the waiter is on-break.

Currently my code runs this correctly, but the "negotiation" is instataneous so you can't really see if the "go on break" button is disabled. You can press it all you want, however if the host won't let that waiter go on break it will never let it. Will this be a problem for grading?

**Comment by choiRyan** [comment]
No but instructor said account for this regardless and this is just a
result of the Host not having that many things to do. (It's not "really"
instantaneous, just fast.)

**Comment by Seioch** [comment]
Cool, thanks!
