### ISSUE TITLE
On Break button?

### ISSUE THREAD

**Issue by 004forever** [usc-csci201-fall2013/restaurant#52]
Does the on-break button have to be a button? Because I implemented it as a checkbox to take advantage of some of the previously implemented amHungry functionality.  It still behaves like it's supposed to: it gets disabled at the right times and triggers the right behaviors, but it's not technically a button.

**Comment by waynchi** [comment]
Crowley said that you can have a checkbox. It just has to be disabled at the right times

**Comment by janicejl** [comment]
As long as it functions properly as a check box it is fine. If we can click the check box to trigger the waiter wanting to go on break. And if he is permitted to go on break, the checkbox get disabled. And once he is back from break the check box is reenabled so that he can go on break again.
