### ISSUE TITLE
Non-Norm: Customers Leaving while waiting outside

### ISSUE THREAD

**Issue by waynchi** [usc-csci201-fall2013/restaurant#53]
Is it okay if I implemented this without using any messages? It works correctly with the customer leaving or staying after a certain amount of time.

**Comment by jaredborner** [comment]
I would say to use messaging for these scenarios. The rubric states the customer is _told_ and then decides whether to stay or leave. I know that probably seems a bit pedantic, but unless a professor has given their okay the rubric is going to be what the assignments are graded by.

But aside from the rubric, another reason to use messaging is to avoid a possible subtle race condition. If you use a timer to run the code that makes the decision to leave, you could end up with the timer "deciding" to leave while the customer agent is scheduling some other (possibly contradictory) action. Whether this occurs and the consequences depend on the specifics of your code, but simply using messaging avoids this.

**Comment by imvincible** [comment]
Although this implementation may work, you should not implement this scenario this way, because agents should not assume anything about other agents without receiving messages. According to agent design, each agent is an independent unit, so the only way for one agent to know the other is to send messages.

**Comment by waynchi** [comment]
Well, it still follow agent methodology because the customer messages the host telling him that he's fed up waiting and is leaving.
However, the host doesn't message the customer.

Also, it is impossible for race conditions to occur because it is occurring within the same thread and the same thread can't really have a race condition with itself. 

I'll type up code for messages for now, but i'd still like to know if my timer mechanic would work.

**Comment by pixelprizm** [comment]
Actually, I believe that when you start a timer, it actually occurs in a new, separate thread.  The customer's scheduler-action thread is free to continue even when the timer calls the run() method, so it's like a short-lived thread that ends after the run() method finishes. Therefore race conditions could still occur.
