### ISSUE TITLE
Normative Scenario  Question

### ISSUE THREAD

**Issue by waynchi** [usc-csci201-fall2013/restaurant#54]
"No customers, cook orders low items from market, when food arrives, then customers arrive"

What does this mean? Is the cook supposed to start off with less food than his "ordering level"? Or do we just spawn a few customers to make it hit that level, and then just wait until the food arrives. And then we make the customers hungry again.

**Comment by jaredborner** [comment]
Start the cook off with less inventory than the ordering threshold. When you run the program the cook should see that he/she needs inventory and order accordingly. Once the cook has been restocked, start spawning customers. The point is that the cook should be able to restock without just checking inventory as it's cooked.

**Comment by waynchi** [comment]
Ok Thanks!

**Comment by xulander** [comment]
Does this mean we start by sending a msg to the cook from the restaurant panel? Unless I'm missing something, we'd need a gui action to get the agents going if we don't do it through the restpanel. And does that mean you graders are fine waiting until the order comes in before adding customers?

Would it be okay if I just order the foods after the first customers start ordering?

**Comment by xulander** [comment]
@jaredborner i dont know how to re-open this issue

**Comment by pixelprizm** [comment]
I believe that you would just call stateChanged() in the startThread() method in agent.Agent.
