### ISSUE TITLE
Normative Scenarios: Markets and Messages

### ISSUE THREAD

**Issue by xulander** [usc-csci201-fall2013/restaurant#56]
I have a 2 part question. One of them I asked in a closed issue, but because I didn't know how to reopen it, I thought it'd just be better if I pair it with my other question.

1) "Tells Cook when order cannot be fulfilled"
For this normative scenario, is it okay that we just load balance the markets? When talking about this, my impression was that it was just like the host-waiter load balancing. I just check to see if the market has enough inventory. If it doesnt, I check the next market. Is this implementation okay? 

2) "No customers, cook orders low items from market, when food arrives, then customers arrive"
Does this mean we start by sending a msg to the cook from the restaurant panel? Unless I'm missing something, we'd need a gui action to get the agents going - unless we do it through the restpanel. And does that mean the graders are fine waiting until the order comes in before adding customers?

Would it be okay if I just order the foods after the first customers start ordering?

**Comment by xulander** [comment]
Or would just putting check inventories at the bottom of the scheduler for the cook suffice for "No customers, cook orders low items..." ? This would mean that the program has already had a scenario occur

**Comment by jakelow** [comment]
1) you can't have the cook check the market inventories like that because it doesn't allow the necessary scenario to occur.

2) you can simply set your cook's starting inventory to low, and then, upon startup, the first thing the cook will see is that he needs to order more food.
