### ISSUE TITLE
Build File Issue!!

### ISSUE THREAD

**Issue by paigekehoe** [usc-csci201-fall2013/restaurant#57]
I tried to add an images file to my build path because when I pushed the file to my repository it got taken out of my eclipse project, but now my project will not run at all.  It throws this exception: 
![screen shot 2013-10-13 at 10 04 22 am](https://f.cloud.github.com/assets/3280005/1322673/9b7b25d2-3441-11e3-9fb0-83053f9e4625.png)

I have tried changing the build file, recloning my entire repository, removing the images directory, but nothing I do works.  I can't test anything or finish my project so if someone knows how to fix this I would be so appreciative!!

**Comment by Seioch** [comment]
Have you tried cleaning and rebuilding? It should re-examine all broken class files and tell you which ones it cannot find.
