### ISSUE TITLE
What happens when Cook is out of a Customer's choice?

### ISSUE THREAD

**Issue by pqseags** [usc-csci201-fall2013/restaurant#60]
The rubric currently states:

(2 points) Reorders when original order is out of stock

(2 points) Animation support for Customer leaving after restaurant runs out of your choice.

So what should the customer do?

**Comment by mcwhitak** [comment]
These describe two different scenarios. The second refers to the customer leaving (due to not having enough money for another choice, etc). This is in the rubric to ensure you have animations for your non-normative scenarios.

So both of them should be done, but in different situations.

**Comment by pqseags** [comment]
Ah, that clears things up. Thanks for the response!
