### ISSUE TITLE
Uploading Without Merge

### ISSUE THREAD

**Issue by lshiffer** [usc-csci201-fall2013/restaurant#62]
Is there a way to upload without merging? 

My code keeps needing to merge then when I download it I have all these HEAD and ¦>>> and random numbers and duplicate functions everywhere that will take hours to fix. 

How can I avoid this happening? Thanks.

**Comment by malively** [comment]
Are you getting conflicts when trying to push? 
Are you working in a different branch than master? 

If you are getting conflicts you should resolve all the conflicts and then re-commit and then be able to push.

If you have a lot of confilcts and think it will take too long to resolve you can do a force push. 
git push --force
This will make your commit head without checking to see if it is fast forward.
Only do a push force if you don't have enough time to resolve your conflicts.

**Comment by janicejl** [comment]
The best way forward is to fix your merge conflicts. 

First commit any changes you have locally on your computer. 
Then do a git pull: This is the step that is probably giving you the <<<HEAD stuffs. 
Fix the code, look at all the sections of <<<HEAD ==== and pick the correct version 
After fixing all conflicts (ctrl+f for HEAD and <<<</>>>>), do a git commit -am "merge fixed." 
Then do a git push. 

This should stop the merge conflicts happening when you do a git pull in future.
