### ISSUE TITLE
Cook updating inventory

### ISSUE THREAD

**Issue by jdgreenberger** [usc-csci201-fall2013/restaurant#63]
In terms of updating inventory, one of the other issues concluded that cooks should update their inventory and buy from the market without first getting an order from a waiter. However, if a cook automatically updates their inventory (perhaps at program startup), the cook will never run out of food: the reorder situation will never occur. How should we solve this?

**Comment by janicejl** [comment]
You may tell the grader as part of you README to restart your restaurant for each different scenario. From there, you should can probably start with a good amount of food, and if the button is click (a hack), the amount of food will reach the need to reorder level, at the start.

**Comment by jdgreenberger** [comment]
Even then, the cook refills at the start and the customer will never order something that isn't in stock (and thus need to reorder).

**Comment by brianykim** [comment]
The cook should order at the start, but it should take a long time for the Market to finally get the shipment to the cook, in that time maybe 30 seconds to a minute, a customer can order something that isn't on the menu. For me  I start with 2 steaks and 2 chickens, and hack somebody based on customer name to order a salad or pizza first. Once the shipment comes in, no problems, but until then they'll reorder until they choose steak or chicken.

**Comment by jakelow** [comment]
you could create a gui to manually enter the inventory for the cook and markets. you could have the cook check the inventory when the amount of food equals a certain amount, greater than zero. so when you set, say, chicken to 0, the cook won't check and restock. and then you'd need to add something where the cook will finally restock after telling a customer who ordered that item to reorder
