### ISSUE TITLE
Can we close multiple issues with a single commit?

### ISSUE THREAD

**Issue by pixelprizm** [usc-csci201-fall2013/restaurant#64]
I've noticed that multiple issues are often handled by the same additions in code, like the "Scenario 1 - Adding a Cashier to the Restaurant" issue and the "Cashier Agent Implementation" issue.  I see how these issues aren't exactly the same as each other, but fixing one, in my case, fixes the other.  Are we able and/or allowed to close multiple issues with a single commit?

**Comment by jaredborner** [comment]
Yes you can close multiple issues with a single commit (ie, `closes #1, closes#2, ...`).

And if that commit was the one that does in fact resolve those issues, then you _should_ close them in the same commit.

**Comment by pixelprizm** [comment]
Cool, thanks
