### ISSUE TITLE
 waiter home position visible

### ISSUE THREAD

**Issue by chadmart** [usc-csci201-fall2013/restaurant#67]
The rubric says, "Make the waiter home position visible. Each waiter should have its own home position." How many different home positions do we have to support? Also, If there more waiters than home positions can we have the other waiters wait off screen?

**Comment by vikrantsinghal** [comment]
If we need a unique position for every waiter, then that's the only thing we can do. We can't possibly fit in more waiters than what the screen permits. What I did was to align them in one horizontal row. My animation panel can have around 15 waiters in that way. So I don't think anybody would be making more waiters than that!

**Comment by choiRyan** [comment]
I'm wondering if each waiter's home position has to be set such that the waiters don't overlap. 
This way you could specify home locations with 2x2px points 8px apart that could support dozens of waiters but they would overlap a bit.

**Comment by jakelow** [comment]
this implementation would be fine. you could have overlap, or not, but either way, i couldn't imagine you needing in excess of 20 waiters. as long as you can support a reasonable amount of waiters, its okay. And after that number has been reached you could have the rest of them line up off screen like they currently do, or just cap the number of waiters.
