### ISSUE TITLE
General Question about Deadline

### ISSUE THREAD

**Issue by xli438** [usc-csci201-fall2013/restaurant#68]
@alghanmi Will v2.2 actually due on 10:59:59 or we kinda have a grace period that if we change some little mistakes before midnight, we will not be considered late submission?

**Comment by alghanmi** [comment]
Details are in the [Submission Procedure](http://www-scf.usc.edu/~csci201/assignments.html) section of the assignments page.

**Comment by xli438** [comment]
Thank you!
