### ISSUE TITLE
Concurrent-Modification Requirement

### ISSUE THREAD

**Issue by pbradshawusc** [usc-csci201-fall2013/restaurant#69]
On the rubric, it suggests we use synchronized lists for the Waiter and catching the ConcurrentModificationError in all other agents. In my code, I had already implemented the synchronized lists in the Cashier, so would it be acceptable for me to keep that as my synchronized lists agent and then catch the error in my waiter and all other agents?

Thank you!

**Comment by vikrantsinghal** [comment]
Wait, doesn't the assignment page say the opposite thing?

**Comment by eerie444** [comment]
The assignments page definitely says the opposite.

**Comment by eerie444** [comment]
And I don't see anything on the rubric about this...

**Comment by pbradshawusc** [comment]
Yeah, I totally misread that, sorry!
