### ISSUE TITLE
Order class

### ISSUE THREAD

**Issue by maciesielka** [usc-csci201-fall2013/restaurant#7]
Prof. Wilczynski's email mentioned that the Order class is an inner class of the CookAgent, while it doesn't explicitly say that it needs to be inner on the rubric.

I was wondering if it necessarily needs to be this way? My implementation allows the WaiterAgent to use the Order class, because I imagine that in a restaurant a Waiter would understand the concept of an order as he/she puts them in. 

For now I've put the Order class declaration in the CookAgent file, but have left it static and available to the package to try and fit the rubric more closely. Any clarification is helpful -- thanks!

**Comment by waynchi** [comment]
This is what I did as well. I assumed it was O.K. because it seemed like Crowley wanted to give us flexibility when we were discussing this in his class. 
So I'm really confused as well.

**Comment by Valakor** [comment]
The rubric states at the beginning that the Waiter should pass a choice and table number, rather than an Order; I'm assuming that means they want us to make Order and inner class of Cook. It is unclear, though.

Need answer @alghanmi

**Comment by lshiffer** [comment]
I create Order in Waiter when customer tells Waiter order and then send Order to Chef which Chef sends back when finished...  Don't understand why Order would be an inner class when Waiter and Cook both can benefit from it.

**Comment by Valakor** [comment]
I had the same implementation, but changed it because the rubric says Orders should be in the Cook. It isn't really necessary to have the Order in the Waiter.
