### ISSUE TITLE
Paying the Market

### ISSUE THREAD

**Issue by dhata** [usc-csci201-fall2013/restaurant#70]
So the Cashier pays the Market's bill in a message, but what does the Market do with the money after? 
Can he just receive the money and print out the confirmation? 
Are we allowed to just print statements in messages?

**Comment by vikrantsinghal** [comment]
Well, the market actually does nothing with the money. So my cashier simply hands over the money to the market and prints out how much money has been paid to which market. I don't think there is anything left to do.

**Comment by jakelow** [comment]
This is correct. As long as the money gets transferred to the market and deducted from the cashier, the requirement is satisfied. The market doesn't need to do anything with the money.

**Comment by xulander** [comment]
Does the cashier always have enough money? Or does the cashier actually have an amount, and may not be able to pay for the food? Do we need to keep track of how much money the cashier has?

**Comment by jakelow** [comment]
the extra credit portion of v2.2A is dealing with the situation in which the cashier does not have enough money to pay the market's bill. So it might be necessary to keep track of the cashier's money.
