### ISSUE TITLE
Animation Upgrade Question

### ISSUE THREAD

**Issue by Yunying** [usc-csci201-fall2013/restaurant#73]
Should the waiter and customer never overlap each other in the waiting area? That means, can they overlap each other when they are moving? And can they waiting in the same rectangle like a deck of cards?

Thank you!

**Comment by Simon-Hou** [comment]
I believe they can when moving. Otherwise, you would need to implement the A*.

**Comment by jakelow** [comment]
The waiters should have their own unique rest positions. However, customers are allowed to overlap with waiters while moving to and from tables.
