### ISSUE TITLE
Synchronising Methods

### ISSUE THREAD

**Issue by vikrantsinghal** [usc-csci201-fall2013/restaurant#74]
The assignment page shows that there are two ways of implementing synchronization. First, synchronizing the list themselves. Second, putting blocks under "Synchronized" keyword, where modification of lists takes place.
So what is the difference between the two? Are both of them complementary, or will usage of only one of them work every time?

**Comment by eerie444** [comment]
You need to do both of those. `Collections.synchronizedList` makes sure that individual method calls on the list (like `add` or `remove`) are thread-safe, but can't help you when you're iterating over the list. That's where `synchronized` blocks come in. Surround any loop that iterates over your list with a `synchronized` block. With those two together, you're safe!

There is another method of dealing with concurrent modification, mentioned in the assignment page. Wrap your scheduler in a `try` block, then `catch (ConcurrentModificationException e)` and return false (or true, works either way tbh).

According to the assignment page, you're supposed to catch the exception in your WaiterAgent, and use `synchronizedList`s everywhere else.

**Comment by dhata** [comment]
do we necessarily have to use the catching method in the Waiter? or can we just use it in a different agent?

**Comment by jakelow** [comment]
no. as long as you have both ways implemented, try-catch and synchronized, it doesn't matter which agents implement which.
