### ISSUE TITLE
Question on adding money between market and cashier

### ISSUE THREAD

**Issue by kyuhyunc** [usc-csci201-fall2013/restaurant#75]
The rubric says that we are supposed to build up the scenario that if there is one order fulfilled by TWO markets, 2 bills paid in full. 

I am confused about how one order can be fulfilled by two markets.

Could anyone explain this clearly?

**Comment by Simon-Hou** [comment]
When the market can only fulfill part of the order, the remaining order will be sent back to the cook and then be sent to a second market. So one order may be fulfilled my one or more markets (maybe even more than 2).
