### ISSUE TITLE
Fixing Old Errors

### ISSUE THREAD

**Issue by mgoulis** [usc-csci201-fall2013/restaurant#77]
Just a general question:

I have certain features from older versions that are not currently working (like the pause button). On the rubric there aren't any deductions listed for old errors and I don't want to spend time hunting down solutions to old problems near the deadline when perfecting the current version is a priority. Will points be deducted for faulty features that do not detract from the V2.2 additions and tests?

Thanks in advance!

**Comment by EliteSoba** [comment]
You're gonna have a hard time releasing a perfect current version if you've still got past errors. Still, there are technically no requirements in the rubric for you to have everything working from previous versions, as long as your normative and most of your nonnorms work. That is, if your _only_ problem is the pause button, then you might be okay.

**Comment by mgoulis** [comment]
Ok, that answered my question. Thanks!
