### ISSUE TITLE
Submission Instructions

### ISSUE THREAD

**Issue by waynchi** [usc-csci201-fall2013/restaurant#8]
All the submission Instructions are TBA. Is there anything specific that we have to do?

Thank you.

**Comment by waynchi** [comment]
Also, the only thing I know to do is tag. What do I tag to the final project? v2.0? "Final 2.0"? 

Thank you !

**Comment by ghost** [comment]
In the past Rami's script has just pulled down whatever is in everyone's repos at the deadline.  Where did you read we had to tag it?

**Comment by waynchi** [comment]
It says to tag it in the rubric. I don't know what to tag it though.

**Comment by alghanmi** [comment]
The [submission instructions page](http://www-scf.usc.edu/~csci201/submission-instructions.html) is not live.

@sciencepro is right, as students who worked with me before would know and automated script will take care of everything :).

Tagging is **optional**, but recommended. You can use a tag like `restaurant-v2.0`. This is a good reference:
http://git-scm.com/book/en/Git-Basics-Tagging#Lightweight-Tags

> Please close the issue if the matter is resolved.
