### ISSUE TITLE
Synchronization Question

### ISSUE THREAD

**Issue by waynchi** [usc-csci201-fall2013/restaurant#82]
Hi, in the instructions it said to put a 
Synchronized ("list variable"){               }
around your 
for(variable c: list variable)
loops

However, if say we used a for( i = 0; i < size; i ++) loop, would we still have to synchronize it?
Would it cause any problems if we synchronized it anyways?

Thank you!

**Comment by imvincible** [comment]
Yep, you still need to use it and actually there is no major difference between these two iterations. Since the synchronizedList is not synchronized during the iteration, you should make sure the list is stable during iteration by yourself.

**Comment by waynchi** [comment]
Thanks
