### ISSUE TITLE
Cashier ynable to pay the market question

### ISSUE THREAD

**Issue by Yunying** [usc-csci201-fall2013/restaurant#85]
On the rubric it says "You end the scenario by telling us how your cashier makes good on the payment."

So I was wondering what does it mean by "end the scenario"? Shall we allow the restaurant to continue operation or just exit the program?

**Comment by imvincible** [comment]
I think "end the scenario" means that you make your restaurant go back to normal, rather than exit the program. Also, make sure that have some feedback, ex: print statement, that tells us how your cashier handle this situation.

**Comment by Yunying** [comment]
Thank you!
