### ISSUE TITLE
Synchronization method 2 return false?

### ISSUE THREAD

**Issue by Simon-Hou** [usc-csci201-fall2013/restaurant#87]
I have problem to return false. If I only have one customer and one waiter, then the synchronized block will make cause concurrent modification error. If it return false, it will never run again, and then stuck there. I changed it to return true, and it works. Can I do this or do I need to stick to the requirement?

**Comment by ukby1234** [comment]
Cuz it should be return true, return false is wrong.

在 2013年11月2日星期六，Fangli Hou 写道：

**Comment by Simon-Hou** [comment]
Thanks!
