### ISSUE TITLE
Unit test will change the variable in CashierAgent to public

### ISSUE THREAD

**Issue by Simon-Hou** [usc-csci201-fall2013/restaurant#88]
I need to access the variable in CashierAgent in Unit Test, and thus change needed private variable to public. I only used them in the Unit test. Will this be considered shared data? Or what should we do to access the private variable in CashierAgent?

**Comment by imvincible** [comment]
It is okay to define data as public, but make sure you don't access this data inside other agent in any circumstance including testing. Ex: Your waiter agent is checking a boolean in cashier agent. I think it is okay to access your agent data in your TestCase class.

**Comment by Valakor** [comment]
From what I understand it's basically unavoidable to make some data in Cashier public for the JUnit testing because you need to check pre and post conditions of every message you send, etc. Just make sure you don't access those public members anywhere but your testing code.

**Comment by Simon-Hou** [comment]
Thank you!
