### ISSUE TITLE
Do we have to use event log in the Unit Test?

### ISSUE THREAD

**Issue by Simon-Hou** [usc-csci201-fall2013/restaurant#89]
I make the mock to print what messages and arguments they received. I remember in the lab the CPs said it is ok. Does this also safisfy the requirement for v2.2?

**Comment by carmiele** [comment]
EventLog was a class created by a previous 201 student, so you do not HAVE to use it. I am not sure if you are ALLOWED to use it, but if the CP's said if it was OK, then I guess you can.

**Comment by Simon-Hou** [comment]
Thank you so much!
