### ISSUE TITLE
Grading and submission

### ISSUE THREAD

**Issue by Seioch** [usc-csci201-fall2013/restaurant#9]
I vaguely remember that we were going to demo our finished PAs to a CP or a TA as our grading procedure, however because the submission page is empty I'm not too sure. Is this correct?

**Comment by alghanmi** [comment]
There is no demo for Assignment 1 and [submission instructions page](http://www-scf.usc.edu/~csci201/submission-instructions.html) is not live.

> Please close the issue if the matter is resolved.
