### ISSUE TITLE
Synchronization issue

### ISSUE THREAD

**Issue by byroncho** [usc-csci201-fall2013/restaurant#91]
I've triple-checked all of my for loops and lists to make sure that I properly implemented the synchronizations, and I've got the entire scheduler for my WaiterAgent surrounded by a try, with the catch(ConcurrentModificationException e) returning false. However, I still have a ConcurrentModificationException occurring between the WaiterAgent and the CookAgent. Any ideas on what I could be doing wrong?

**Comment by Valakor** [comment]
Did you declare all your lists as such:
`List<Something> myList = Collections.synchronizedList(new ArrayList<Something>());`
Using synchronized blocks only makes iterating over a list thread-safe, but doesn't make method calls on the list thread-safe (i.e. `myList.add(something)`). Declaring a list as a synchronizedList makes these operations thread-safe.

To be safe, I basically made every single data structure I used a synchronized structure (including my HashMaps and Hashtables describing my foods classes, menu items, etc.) Perhaps when you subtract food from your current stock in cook after a waiter orders a meal, you modify your list of available foods when it's being iterated over somewhere else?

**Comment by byroncho** [comment]
Figured out my problem, thanks for the help.
