### ISSUE TITLE
JUnit 3 Library

### ISSUE THREAD

**Issue by choiRyan** [usc-csci201-fall2013/restaurant#93]
When I push my program to JUnit 3, then clone it elsewhere and run it on Eclipse, JUnit 3 is not referenced as it is in my original program. Though it's a 1-click fix, the rubric states that any alterations to code will result in up to 25 pts.

Where are the references to the JUnit 3 library stored within the program?

**Comment by ukby1234** [comment]
No worry, it's a project setting issue. There won't be any deduction.

在 2013年11月2日星期六，Ryan Choi 写道：

**Comment by choiRyan** [comment]
Thanks for the clarification.
