### ISSUE TITLE
JUnit, assigning values

### ISSUE THREAD

**Issue by aitbayev** [usc-csci201-fall2013/restaurant#96]
I'm trying to assign money to my customer(mock customer),
 Customer.setMoney(10.99) ;

but I keep getting 0.0 after running it.

**Comment by EliteSoba** [comment]
I don't know if your code on Github is updated or not, but your setMoney function doesn't do anything.

**Comment by aitbayev** [comment]
should write actual implementation of setMoney in MockCustomer?

**Comment by EliteSoba** [comment]
Well your money is never going to be set unless you set it yourself.

**Comment by aitbayev** [comment]
I set my money randomly when i add customer. But with testing I should set money myself, so I call setMoney(). Is this right?
